import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { InterestProvider } from "@/context/InterestContext";
import { EventProvider } from "@/context/EventContext";
import Sidebar from "@/components/core/Sidebar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-slate-900`}
      >
        <InterestProvider>
          <EventProvider>
          <div className="flex mon-h-screen">
            <Sidebar />
            <main className="p-4">
              {children}
            </main>
          </div>
          </EventProvider>
        </InterestProvider>
      </body>
    </html>
  );
}
